added web site pages html
INF6420/ss23-manzar79 pull request #3
Opened 2023-06-01 20:47 UTC by manzar79

2023-06-05 14:40 UTC, axamei requested changes
please rename the files so they don't have spaces, e.g., `about-us.html`

2023-06-06 13:29 UTC, manzar79 commented
Removed spaces from html file names @axamei

2023-06-07 14:01 UTC, axamei requested changes
Please use `/` instead of `\`

2023-06-07 14:01 UTC, axamei commented on About-Us.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
Please use `/` instead of `\`

2023-06-07 14:01 UTC, axamei commented on Contact-Us.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
Please use `/` instead of `\`

2023-06-07 14:01 UTC, axamei commented on Upcoming-Events.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
Please use `/` instead of `\`

2023-06-07 14:01 UTC, axamei commented on index.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
Please use `/` instead of `\`

2023-06-11 15:06 UTC, manzar79 commented on About-Us.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
updated code with /

2023-06-11 15:07 UTC, manzar79 commented on Contact-Us.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
updated code with /

2023-06-11 15:07 UTC, manzar79 commented on Upcoming-Events.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
updated code with /

2023-06-11 15:07 UTC, manzar79 commented on index.html
> +            <img src="booksale\logo.png" alt="Logo for Site">
updated code with /

2023-06-11 15:07 UTC, manzar79 commented
updated code with /

2023-06-13 01:05 UTC, axamei approved these changes

2023-06-13 01:06 UTC, merged